#FROM openjdk:8-jre-slim
#FROM java:openjdk-8-jre-alpine
FROM jkremser/mini-jre:8

ARG OSHINKO_VERSION=v0.5.2
ENV OSHINKO_VERSION=${OSHINKO_VERSION} \
    JAVA_OPTS="-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
LABEL OSHINKO_VERSION=${OSHINKO_VERSION} \
      BASE_IMAGE="jkremser/mini-jre:8"

ADD target/spark-operator-*.jar /spark-operator.jar

RUN set -x && \
  wget https://github.com/radanalyticsio/oshinko-cli/releases/download/${OSHINKO_VERSION}/oshinko_${OSHINKO_VERSION}_linux_386.tar.gz && \
  wget https://github.com/radanalyticsio/oshinko-cli/releases/download/${OSHINKO_VERSION}/SHA256-CHECKSUM && \
  cat SHA256-CHECKSUM | grep oshinko_${OSHINKO_VERSION}_linux_386.tar.gz > SHA256-CHECKSUM-filtered && \
  sha256sum -c SHA256-CHECKSUM-filtered && \
  tar -xzf ./oshinko_${OSHINKO_VERSION}_linux_386.tar.gz && \
  rm ./oshinko_${OSHINKO_VERSION}_linux_386.tar.gz SHA256-CHECKSUM SHA256-CHECKSUM-filtered

CMD ["/usr/bin/java", "-Dvertx.cacheDirBase=/tmp", "-jar", "/spark-operator.jar"]