#FROM openjdk:8-jre-slim
#FROM java:openjdk-8-jre-alpine
FROM jkremser/mini-jre:8

ENV JAVA_OPTS="-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"

LABEL BASE_IMAGE="jkremser/mini-jre:8"

ADD target/spark-operator-*.jar /spark-operator.jar

CMD ["/usr/bin/java", "-Dvertx.cacheDirBase=/tmp", "-jar", "/spark-operator.jar"]
