kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1beta1
metadata:
  name: sparkclusters.radanalytics.io
spec:
  group: radanalytics.io
  names:
    kind: sparkcluster
    listKind: sparkclusterList
    plural: sparkclusters
    singular: sparkcluster
  scope: Namespaced
  version: v1

---

kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1beta1
metadata:
  name: apps.radanalytics.io
spec:
  group: radanalytics.io
  names:
    kind: app
    listKind: appList
    plural: apps
    singular: app
  scope: Namespaced
  version: v1

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-operator

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: edit-spark-resources
rules:
- apiGroups:
  - radanalytics.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - configmaps
  verbs:
  - "*"

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: spark-operator-edit-spark-resources
subjects:
- kind: ServiceAccount
  name: spark-operator
roleRef:
  kind: Role
  name: memcached-operator
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: sparkoperator.v0.0.1
  namespace: default
  annotations: 'alm-examples: [{"apiVersion": "radanalytics.io/v1","kind": "sparkcluster","metadata": {"name": "sparky-cluster"},"spec": {"master": { "replicas": 1 },"sparkConfiguration": [{"name": "spark.executor.memory","value": "2g"}],"worker": {"replicas": 2}}}]'
spec:
  displayName: Apache Spark Operator
  description: |
    **Apache Spark** is foo
    # Before you start
    todo: this
    
    Usage:
    ```
    # create cluster
    cat <<EOF | kubectl create -f -
    apiVersion: radanalytics.io/v1
    kind: sparkcluster
    metadata:
      name: my-spark-cluster
    spec:
      worker:
        replicas: 2
    EOF
    ```
  install: 
    strategy: deployment
    spec:
      permissions:
      - serviceAccountName: spark-operator
        rules:
        - apiGroups:
          - radanalytics.io
          resources:
          - "*"
          verbs:
          - "*"
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - configmaps
          verbs:
          - "*"
      deployments: 
      - name: spark-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              app.kubernetes.io/name: spark-operator
              app.kubernetes.io/version: v0.1.5-v1alpha1
          template:
            metadata:
              labels:
                app.kubernetes.io/name: spark-operator
                app.kubernetes.io/version: v0.1.5-v1alpha1
            spec:
              containers:
                - name: spark-operator
                  image: radanalyticsio/spark-operator:latest-released
                  imagePullPolicy: Always
                  env:
                  - name: CRD
                    value: "true"
                  resources:
                    requests:
                      memory: "64Mi"
                      cpu: "250m"
                    limits:
                      memory: "128Mi"
                      cpu: "500m"
              restartPolicy: Always
              terminationGracePeriodSeconds: 5
              serviceAccountName: spark-operator
              serviceAccount: spark-operator
  customresourcedefinitions:
    owned:
      - description: Represents an Apache Spark cluster
        displayName: Spark Cluster
        kind: sparkcluster
        name: sparkcluster.radanalytics.io
        version: v1
        resources:
          - kind: Deployment
            version: v1beta2
          - kind: ReplicaSet
            version: v1beta2
          - kind: Pod
            version: v1
        specDescriptors:
          - description: The desired number of the workers in the cluster.
            displayName: Worker Nodes
            path: worker.replicas
            x-descriptors:
              - 'urn:alm:descriptor:com.tectonic.ui:podCount'
          - description: The desired number of the masters in the cluster.
            displayName: Master Nodes
            path: master.replicas
            x-descriptors:
              - 'urn:alm:descriptor:com.tectonic.ui:podCount'
        statusDescriptors:
          - description: The current status of the application.
            displayName: Status
            path: phase
            x-descriptors:
              - 'urn:alm:descriptor:io.kubernetes.phase'
          - description: Explanation for the current status of the application.
            displayName: Status Details
            path: reason
            x-descriptors:
              - 'urn:alm:descriptor:io.kubernetes.phase:reason'
  keywords:
    - spark
  provider:
    name: Radanalytics.io
    url: www.radanalytics.io
  maturity: alpha
  version: 0.0.1
  maintainers:
    - email: jkremser@redhat.com
      name: Red Hat, Inc.
  labels:
    alm-owner-enterprise-app: spark-operator
    alm-status-descriptors: spark-operator.v0.0.1
