apiVersion: v1
kind: ConfigMap
metadata:
  name: ntlk-example
  labels:
    radanalytics.io/kind: sparkapplication
data:
  config: |-
    image: jkremser/spark-operator:2.4.0-ntlk
    type: Python
    mainApplicationFile: local:///app.py
    deps:
      pyFiles:
        - local:///deps.zip
    driver:
      cores: 0.4
      coreLimit: 400m
      memory: 600m